name: Docs Cleanup CI

# delete branch documentation when a branch is deleted
# also allow manually deleting a documentation version
on:
  delete:
  workflow_dispatch:
    inputs:
      version:
        description: "documentation version"
        required: true
        type: string

jobs:
  remove:
    if: github.event.ref_type == 'branch' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          branch: gh-pages

      - name: removing documentation for branch ${{ github.event.ref }}
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: echo rm -r .github/pages/${{ github.event.ref }}

      - name: manually removing documentation version ${{ github.event.inputs.version }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo rm -r .github/pages/${{ github.event.inputs.version }}
